# Specifications of files and symlinks for the dev.eessi.io CVMFS repository.
# Paths for files and symlinks should be relative to the root of the repository.
---
directories: [] # noqa: var-naming[no-role-prefix]

files: # noqa: var-naming[no-role-prefix]
  - name: cvmfsdirtab-dev.eessi.io
    dest: '.cvmfsdirtab'
    mode: '644'

  - name: README.dev
    dest: 'README'
    mode: '644'

symlinks: [] # noqa: var-naming[no-role-prefix]
