# Specifications of files and symlinks for the software.eessi.io CVMFS repository.
# Paths for files and symlinks should be relative to the root of the repository.
---
directories:
  - name: init/modules/EESSI
    mode: '755'

files:
  - name: .cvmfsdirtab
    dest: ''
    mode: '644'

  - name: README.eessi
    dest: ''
    mode: '644'

symlinks:
  host_injections: '$(EESSI_HOST_INJECTIONS:-/opt/eessi)'
  init/modules/EESSI/2023.06.lua: /cvmfs/software.eessi.io/versions/2023.06/init/modules/EESSI/2023.06.lua
