name: Build packages

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-packages:

    runs-on: ubuntu-latest

    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v2

    - name: ansible check with debian:stretch
      uses: roles-ansible/check-ansible-debian-stretch-action@master
      with:
        targets: "./build-packages.yml"
        hosts: "localhost"

    - name: upload deb package as artifact
      uses: actions/upload-artifact@v2
      with:
        name: Deb package
        path: ${{ github.workspace }}/build/*.deb

    - name: upload rpm package as artifact
      uses: actions/upload-artifact@v2
      with:
        name: RPM package
        path: ${{ github.workspace }}/build/noarch/*.rpm
